### ISSUE TITLE
error loading todos from mockapi (certificate)

### ISSUE THREAD

**Issue by kriswep** [christiannwamba/scotch-react-todo#1]
You are reading the todos from the mockapi service via https. it seems they have misconfigured theit https access right now.
At least, i'm getting certificate warnings opening https://57b1924b46b57d1100a3c3f8.mockapi.io/api/todos

**Comment by jakimcho** [comment]
Hello,
First I would  like to thanks for this tutorial. It helped me a lot.
I think I found the problem with **todos** not loading. It is because the mock API response contains some text values that are not strings, they are objects instead. To fix this and warnings because of duplicated todos' keys I amend the **componentDidMount()** implementation on [line 62](https://github.com/christiannwamba/scotch-react-todo/blob/f25e1f00a7ff7dd1b9435678cb9ac5398c254d2d/src/index.jsx#L62) from index.jsx:
```
	componentDidMount(){
    // Make HTTP reques with Axios
    axios.get(this.apiURL)
      .then((res) => {
      	let temp = [];
/*
	1. The rest API returns raw data that cannot be rendered by TODO component -> some of the "text" values are objects
	2. There are some objects from the response that have one and the same id.
	here we are filtering 1 and 2 points
*/
      	let filteredData = res.data.filter( (obj) => {
      		if ((temp.indexOf(obj.id) < 0) && !(obj.text instanceof Object || obj.text === "")){
      			temp.push(obj.id);
      			return true;
      		}else{
      			return false;
      		}
      	});
        this.setState({data: filteredData});
      });
  }
```
